### ISSUE TITLE
Child Profile Paragraph Buckets

### ISSUE THREAD

**Issue by communicationsmare** [autoboxer/MARE#199]
The following are the four text boxes that should be created in the Child's Record which will populate their visible child profile.  The goal is to prompt the MARE worker to make sure the following info is in each box although they will create the narrative.

Intro: Hi my name is ________________ and first-person quote
Box 1: Age, Race, Interests, Hobbies, Strengths
Box 2: Physical, Social, Emotional and Academic Functioning
Box 3: Legal Status, Sibling/Family Contact, Family Constellation and Placement requirements

**Comment by autoboxer** [comment]
from phone conversation with Lisa on April 6th:

Buckets for creating profile page:
Intro: Hi my name is Name and Quote
1P: Age, Race, Interests, Hobbies, Strengths
2P: Physical Social and Emotional Needs
3P: Legal Status, Sibling/Family Contact, Family Constellation and Placement requirements
 
Buckets on Child Registration Form that should be replicated in child’s record:
Physical Needs
Intellectual special needs (added by Lisa on the phone call)
Social Needs
Emotional Needs/Trauma History
Interests, Talents and Aspirations
School Life: (Child’s academic functioning, grade level, school behavior, peer relationships)
Family Life: (Child’s interaction and behavior in a family or residential setting)
Personality (How does child or others describe him/herself? What is unique about this child (e.g. sexual orientation/gender identity, temperament, sense of humor, etc.)
Other Recruitment Considerations (Qualities of the ideal family, child’s wishes for a family, worker’s recommendation, geographical considerations)

**Comment by autoboxer** [comment]
Review with @lisafunaro 

changes made to the form:

- added *Social Needs* text area
- removed *Is child receiving therapy?* radio buttons
- changed label from *Emotional Special Needs* to *Emotional Needs/Trauma History*
- removed *Other Considerations* list (Fire Setting, LGBTQ Youth, etc.)
- removed *Other considerations for placement* text area
- removed *Please indicate areas to be avoided in recruitment* text area
- removed *Individual/Personality: How does child describe him/herself?* text area
- removed *Interests: (Describe what child enjoys doing.)* text area
- removed *Talents: (Describe unique aspects of child in terms of what he/she does best.)* text area
- removed *Special Needs: (Briefly describe child’s disabilities, behavioral difficulties, therapy, medication.)* text area
- removed *Placement Requirements: (Include what child wants in a family and worker’s recommendations.)* text area
- removed *If this child could have one wish, What would it be?* text box
- changed label from *Aspirations: (Describe what child wants to be in the future –career or educational goals.)* to *Interests, Talents and Aspirations: (Describe what child wants to be in the future –career or educational goals.)*
- moved *School Life* text area below *Family Life* text area
- added *Personality (How does child or others describe him/herself? What is unique about this child (e.g. sexual orientation/gender identity, temperament, sense of humor, etc.)* text area
- added *Other Recruitment Considerations (Qualities of the ideal family, child’s wishes for a family, worker’s recommendation, geographical considerations)* text area


changes made to the model:

- added *social needs* dropdown (mild, moderate, severe)
- added *socail needs* description box

**There's more to do, review it with @lisafunaro to make sure it's correct**

**Comment by lisafunaro** [comment]
Hi Jared –

I’ve gone thru this with a fine toothed comb!  Here are some edits:

In Child Model:

-          Change the following left hand titles:

o   Let me tell you more about myself…  to 1st paragraph

o   And here’s what others say… to 2nd paragraph

o   If I could have my own special wish…. To 3rd paragraph

-          All the dropdowns for physical needs, emotional needs,
intellectual needs, social needs need to have the text box appear even if
none is chosen (because these buckets are only text boxes on the child
registration form)

-          The fields that need a home can be placed in this order right
after social needs

-          Add text box for Interests, Talents & Aspirations – put it after
social needs and before school life



Edit to Child registration form:

-          Add back Other Considerations list (Fire Setting, LGBTQ Youth,
etc.)





Everything else looks good.  See you today at 4:30!



Lisa





*Lisa K. Funaro LICSW*

Executive Director

*Massachusetts Adoption Resource Exchange, Inc. (MARE)*

45 Franklin Street, 5th Floor, Boston, MA  02110

ph: (617) 542-3678  ext. 111  Fax: (617) 542-1006

lisaf@MAREinc.org

www.MAREinc.org <http://www.mareinc.org/>

*MARE* <http://www.mareinc.org/>* - Finding adoptive **families for
children in foster care since 1957.*









*From:* Jared Collier [mailto:notifications@github.com]
*Sent:* Sunday, April 16, 2017 8:53 AM
*To:* autoboxer/MARE
*Cc:* lisafunaro; Mention
*Subject:* Re: [autoboxer/MARE] Child Profile Paragraph Buckets (#199)



Review with @lisafunaro <https://github.com/lisafunaro>

changes made to the form:

   - added *Social Needs* text area
   - removed *Is child receiving therapy?* radio buttons
   - changed label from *Emotional Special Needs* to *Emotional
   Needs/Trauma History*
   - removed *Other Considerations* list (Fire Setting, LGBTQ Youth, etc.)
   - removed *Other considerations for placement* text area
   - removed *Please indicate areas to be avoided in recruitment* text area
   - removed *Individual/Personality: How does child describe him/herself?*
   text area
   - removed *Interests: (Describe what child enjoys doing.)* text area
   - removed *Talents: (Describe unique aspects of child in terms of what
   he/she does best.)* text area
   - removed *Special Needs: (Briefly describe child’s disabilities,
   behavioral difficulties, therapy, medication.)* text area
   - removed *Placement Requirements: (Include what child wants in a family
   and worker’s recommendations.)* text area
   - removed *If this child could have one wish, What would it be?* text box
   - changed label from *Aspirations: (Describe what child wants to be in
   the future –career or educational goals.)* to *Interests, Talents and
   Aspirations: (Describe what child wants to be in the future –career or
   educational goals.)*
   - moved *School Life* text area below *Family Life* text area
   - added *Personality (How does child or others describe him/herself?
   What is unique about this child (e.g. sexual orientation/gender identity,
   temperament, sense of humor, etc.)* text area
   - added *Other Recruitment Considerations (Qualities of the ideal
   family, child’s wishes for a family, worker’s recommendation, geographical
   considerations)* text area

changes made to the model:

   - added *social needs* dropdown (mild, moderate, severe)
   - added *socail needs* description box

*There's more to do, review it with @lisafunaro
<https://github.com/lisafunaro> to make sure it's correct*

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/autoboxer/MARE/issues/199#issuecomment-294350186>, or mute
the thread
